export const NSE_STOCKS = [
  // Nifty 50
  { symbol: "RELIANCE.NS", name: "Reliance Industries" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank" },
  { symbol: "INFY.NS", name: "Infosys" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever" },
  { symbol: "ITC.NS", name: "ITC" },
  { symbol: "SBIN.NS", name: "State Bank of India" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank" },
  { symbol: "LT.NS", name: "Larsen & Toubro" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies" },
  { symbol: "AXISBANK.NS", name: "Axis Bank" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints" },
  { symbol: "TITAN.NS", name: "Titan Company" },
  { symbol: "WIPRO.NS", name: "Wipro" },
  { symbol: "NESTLEIND.NS", name: "Nestle India" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors" },
  { symbol: "ZOMATO.NS", name: "Zomato" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corp" },
  { symbol: "ONGC.NS", name: "Oil & Natural Gas Corp" },
  { symbol: "NTPC.NS", name: "NTPC" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel" },
  { symbol: "TECHM.NS", name: "Tech Mahindra" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra" },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement" },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories" },
  { symbol: "GRASIM.NS", name: "Grasim Industries" },
  { symbol: "DRREDDY.NS", name: "Dr. Reddy's Laboratories" },
  { symbol: "CIPLA.NS", name: "Cipla" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors" },
  { symbol: "BPCL.NS", name: "Bharat Petroleum" },
  { symbol: "COALINDIA.NS", name: "Coal India" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products" },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries" },
  { symbol: "SHREECEM.NS", name: "Shree Cement" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries" },
  // Nifty Next 50
  { symbol: "VEDL.NS", name: "Vedanta" },
  { symbol: "DABUR.NS", name: "Dabur India" },
  { symbol: "GODREJCP.NS", name: "Godrej Consumer Products" },
  { symbol: "PIDILITIND.NS", name: "Pidilite Industries" },
  { symbol: "SIEMENS.NS", name: "Siemens India" },
  { symbol: "HAVELLS.NS", name: "Havells India" },
  { symbol: "TATAPOWER.NS", name: "Tata Power" },
  { symbol: "INDIGO.NS", name: "InterGlobe Aviation (IndiGo)" },
  { symbol: "DMART.NS", name: "Avenue Supermarts (D-Mart)" },
  { symbol: "NAUKRI.NS", name: "Info Edge (Naukri)" },
  { symbol: "PAYTM.NS", name: "One97 Communications (Paytm)" },
  { symbol: "NYKAA.NS", name: "FSN E-Commerce Ventures (Nykaa)" },
  { symbol: "POLICYBZR.NS", name: "PB Fintech (PolicyBazaar)" },
  { symbol: "IRCTC.NS", name: "IRCTC" },
  { symbol: "IRFC.NS", name: "Indian Railway Finance Corp" },
  { symbol: "IOC.NS", name: "Indian Oil Corporation" },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics" },
  { symbol: "BEL.NS", name: "Bharat Electronics" },
  { symbol: "DLF.NS", name: "DLF" },
  { symbol: "GODREJPROP.NS", name: "Godrej Properties" },
  { symbol: "OBEROIRLTY.NS", name: "Oberoi Realty" },
  { symbol: "PRESTIGE.NS", name: "Prestige Estates" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda" },
  { symbol: "PNB.NS", name: "Punjab National Bank" },
  { symbol: "CANBK.NS", name: "Canara Bank" },
  { symbol: "UNIONBANK.NS", name: "Union Bank of India" },
  { symbol: "FEDERALBNK.NS", name: "Federal Bank" },
  { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank" },
  { symbol: "BANDHANBNK.NS", name: "Bandhan Bank" },
  { symbol: "IDEA.NS", name: "Vodafone Idea" },
  { symbol: "FORTIS.NS", name: "Fortis Healthcare" },
  { symbol: "MAXHEALTH.NS", name: "Max Healthcare" },
  { symbol: "COLPAL.NS", name: "Colgate-Palmolive India" },
  { symbol: "MARICO.NS", name: "Marico" },
  { symbol: "EMAMILTD.NS", name: "Emami" },
  { symbol: "ZYDUSLIFE.NS", name: "Zydus Lifesciences" },
  { symbol: "TORNTPHARM.NS", name: "Torrent Pharmaceuticals" },
  { symbol: "LUPIN.NS", name: "Lupin" },
  { symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma" },
  { symbol: "BIOCON.NS", name: "Biocon" },
  { symbol: "IPCALAB.NS", name: "IPCA Laboratories" },
  { symbol: "MUTHOOTFIN.NS", name: "Muthoot Finance" },
  { symbol: "MANAPPURAM.NS", name: "Manappuram Finance" },
  { symbol: "CHOLAFIN.NS", name: "Cholamandalam Investment" },
  { symbol: "RECLTD.NS", name: "REC" },
  { symbol: "PFC.NS", name: "Power Finance Corporation" },
  { symbol: "LICHSGFIN.NS", name: "LIC Housing Finance" },
  { symbol: "ADANIGREEN.NS", name: "Adani Green Energy" },
  { symbol: "ADANIPOWER.NS", name: "Adani Power" },
  { symbol: "ADANITRANS.NS", name: "Adani Transmission" },
  { symbol: "ADANIWILMAR.NS", name: "Adani Wilmar" },
  { symbol: "AWL.NS", name: "Adani Wilmar" },
  { symbol: "ATGL.NS", name: "Adani Total Gas" },
  // Midcap popular
  { symbol: "DEEPAKNTR.NS", name: "Deepak Nitrite" },
  { symbol: "FLUOROCHEM.NS", name: "Gujarat Fluorochemicals" },
  { symbol: "NAVINFLUOR.NS", name: "Navin Fluorine" },
  { symbol: "TATACHEM.NS", name: "Tata Chemicals" },
  { symbol: "UPL.NS", name: "UPL" },
  { symbol: "COROMANDEL.NS", name: "Coromandel International" },
  { symbol: "JUBLFOOD.NS", name: "Jubilant FoodWorks" },
  { symbol: "WESTLIFE.NS", name: "Westlife Foodworld" },
  { symbol: "DEVYANI.NS", name: "Devyani International" },
  { symbol: "CESC.NS", name: "CESC" },
  { symbol: "TORNTPOWER.NS", name: "Torrent Power" },
  { symbol: "NHPC.NS", name: "NHPC" },
  { symbol: "SJVN.NS", name: "SJVN" },
  { symbol: "SUZLON.NS", name: "Suzlon Energy" },
  { symbol: "INOXWIND.NS", name: "Inox Wind" },
  { symbol: "BOSCHLTD.NS", name: "Bosch India" },
  { symbol: "MOTHERSON.NS", name: "Samvardhana Motherson" },
  { symbol: "BHARATFORG.NS", name: "Bharat Forge" },
  { symbol: "CUMMINSIND.NS", name: "Cummins India" },
  { symbol: "EXIDEIND.NS", name: "Exide Industries" },
  { symbol: "TVSMOTOR.NS", name: "TVS Motor" },
  { symbol: "MRF.NS", name: "MRF" },
  { symbol: "CEATLTD.NS", name: "CEAT" },
  { symbol: "APOLLOTYRE.NS", name: "Apollo Tyres" },
  { symbol: "PGHL.NS", name: "Procter & Gamble Hygiene" },
  { symbol: "GRANULES.NS", name: "Granules India" },
  // IT Sector
  { symbol: "MPHASIS.NS", name: "Mphasis" },
  { symbol: "LTIM.NS", name: "LTIMindtree" },
  { symbol: "LTTS.NS", name: "L&T Technology Services" },
  { symbol: "PERSISTENT.NS", name: "Persistent Systems" },
  { symbol: "COFORGE.NS", name: "Coforge" },
  { symbol: "KPIT.NS", name: "KPIT Technologies" },
  { symbol: "TANLA.NS", name: "Tanla Platforms" },
  { symbol: "ZENSAR.NS", name: "Zensar Technologies" },
  { symbol: "RATEGAIN.NS", name: "RateGain Travel Technologies" },
  { symbol: "MAPMYIND.NS", name: "MapmyIndia (C.E. Info Systems)" },
  { symbol: "TATAELXSI.NS", name: "Tata Elxsi" },
  { symbol: "HEXAWARE.NS", name: "Hexaware Technologies" },
  { symbol: "CYIENT.NS", name: "Cyient" },
  { symbol: "MASTEK.NS", name: "Mastek" },
  { symbol: "NIITLTD.NS", name: "NIIT" },
  { symbol: "INTELLECT.NS", name: "Intellect Design Arena" },
  { symbol: "OFSS.NS", name: "Oracle Financial Services" },
  // Banking & Finance
  { symbol: "YESBANK.NS", name: "Yes Bank" },
  { symbol: "KARURVYSYA.NS", name: "Karur Vysya Bank" },
  { symbol: "SOUTHBANK.NS", name: "South Indian Bank" },
  { symbol: "DCBBANK.NS", name: "DCB Bank" },
  { symbol: "CSBBANK.NS", name: "CSB Bank" },
  { symbol: "EQUITASBNK.NS", name: "Equitas Small Finance Bank" },
  { symbol: "UJJIVANSFB.NS", name: "Ujjivan Small Finance Bank" },
  { symbol: "SURYODAY.NS", name: "Suryoday Small Finance Bank" },
  { symbol: "AUBANK.NS", name: "AU Small Finance Bank" },
  { symbol: "ESAFSFB.NS", name: "ESAF Small Finance Bank" },
  { symbol: "JKBANK.NS", name: "Jammu & Kashmir Bank" },
  { symbol: "LAKSHVILAS.NS", name: "Lakshmi Vilas Bank" },
  { symbol: "RBLBANK.NS", name: "RBL Bank" },
  { symbol: "NUVAMA.NS", name: "Nuvama Wealth" },
  { symbol: "ANGELONE.NS", name: "Angel One" },
  { symbol: "MOTILALOFS.NS", name: "Motilal Oswal Financial" },
  { symbol: "IIFL.NS", name: "IIFL Finance" },
  { symbol: "PCBL.NS", name: "PCBL" },
  { symbol: "SUNDARMFIN.NS", name: "Sundaram Finance" },
  { symbol: "SHRIRAMFIN.NS", name: "Shriram Finance" },
  { symbol: "BAJAJHLDNG.NS", name: "Bajaj Holdings" },
  { symbol: "PNBHOUSING.NS", name: "PNB Housing Finance" },
  { symbol: "CANFINHOME.NS", name: "Can Fin Homes" },
  { symbol: "GRUH.NS", name: "Gruh Finance" },
  { symbol: "HOMEFIRST.NS", name: "Home First Finance" },
  { symbol: "APTUS.NS", name: "Aptus Value Housing Finance" },
  // FMCG
  { symbol: "VBL.NS", name: "Varun Beverages" },
  { symbol: "TATACOMMUNI.NS", name: "Tata Communications" },
  { symbol: "RADICO.NS", name: "Radico Khaitan" },
  { symbol: "UNITEDSPIRIT.NS", name: "United Spirits" },
  { symbol: "ABFRL.NS", name: "Aditya Birla Fashion" },
  { symbol: "TRENT.NS", name: "Trent" },
  { symbol: "VEDANT.NS", name: "Vedant Fashions (Manyavar)" },
  { symbol: "RELAXO.NS", name: "Relaxo Footwears" },
  { symbol: "BATA.NS", name: "Bata India" },
  { symbol: "PAGEIND.NS", name: "Page Industries (Jockey)" },
  { symbol: "KPRMILL.NS", name: "KPR Mill" },
  { symbol: "RAYMOND.NS", name: "Raymond" },
  { symbol: "ARVIND.NS", name: "Arvind" },
  { symbol: "VARDHMAN.NS", name: "Vardhman Textiles" },
  // Pharma & Healthcare
  { symbol: "MANKIND.NS", name: "Mankind Pharma" },
  { symbol: "ALKEM.NS", name: "Alkem Laboratories" },
  { symbol: "ABBOTINDIA.NS", name: "Abbott India" },
  { symbol: "PFIZER.NS", name: "Pfizer India" },
  { symbol: "GLAXO.NS", name: "GSK Pharmaceuticals" },
  { symbol: "SANOFI.NS", name: "Sanofi India" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharma" },
  { symbol: "GLENMARK.NS", name: "Glenmark Pharmaceuticals" },
  { symbol: "GRANULES.NS", name: "Granules India" },
  { symbol: "NATCOPHARM.NS", name: "Natco Pharma" },
  { symbol: "AJANTPHARM.NS", name: "Ajanta Pharma" },
  { symbol: "SUVEN.NS", name: "Suven Pharmaceuticals" },
  { symbol: "LAURUS.NS", name: "Laurus Labs" },
  { symbol: "DIVI.NS", name: "Divi's Laboratories" },
  { symbol: "STRIDES.NS", name: "Strides Pharma" },
  { symbol: "ERIS.NS", name: "Eris Lifesciences" },
  { symbol: "JB.NS", name: "JB Chemicals" },
  { symbol: "SYMPHONY.NS", name: "Symphony" },
  { symbol: "ASTER.NS", name: "Aster DM Healthcare" },
  { symbol: "YATHARTH.NS", name: "Yatharth Hospital" },
  { symbol: "KIMS.NS", name: "KIMS Health" },
  // Auto & EV
  { symbol: "MAHINDRA.NS", name: "Mahindra & Mahindra" },
  { symbol: "OLACABS.NS", name: "Ola Electric" },
  { symbol: "OLA.NS", name: "Ola Electric Mobility" },
  { symbol: "HMCL.NS", name: "Hero MotoCorp" },
  { symbol: "BALKRISIND.NS", name: "Balkrishna Industries" },
  { symbol: "TIINDIA.NS", name: "Tube Investments (Murugappa)" },
  { symbol: "SCHAEFFLER.NS", name: "Schaeffler India" },
  { symbol: "SUNDRMFAST.NS", name: "Sundram Fasteners" },
  { symbol: "ENDURANCE.NS", name: "Endurance Technologies" },
  { symbol: "SUPRAJIT.NS", name: "Suprajit Engineering" },
  { symbol: "MAZDOCK.NS", name: "Mazagon Dock" },
  { symbol: "COCHINSHIP.NS", name: "Cochin Shipyard" },
  { symbol: "GRINDWELL.NS", name: "Grindwell Norton" },
  // Energy & Infra
  { symbol: "GAIL.NS", name: "GAIL India" },
  { symbol: "PETRONET.NS", name: "Petronet LNG" },
  { symbol: "GUJARATGAS.NS", name: "Gujarat Gas" },
  { symbol: "MGL.NS", name: "Mahanagar Gas" },
  { symbol: "IGL.NS", name: "Indraprastha Gas" },
  { symbol: "GUJGASLTD.NS", name: "Gujarat Gas" },
  { symbol: "CPCB.NS", name: "Central Pollution Control Board" },
  { symbol: "KEC.NS", name: "KEC International" },
  { symbol: "KALPATPOWR.NS", name: "Kalpataru Power" },
  { symbol: "APLAPOLLO.NS", name: "APL Apollo Tubes" },
  { symbol: "JINDALSTEEL.NS", name: "Jindal Steel & Power" },
  { symbol: "JSPL.NS", name: "Jindal Steel & Power" },
  { symbol: "SAIL.NS", name: "Steel Authority of India" },
  { symbol: "NATIONALUM.NS", name: "National Aluminium" },
  { symbol: "HINDCOPPER.NS", name: "Hindustan Copper" },
  { symbol: "NMDC.NS", name: "NMDC" },
  { symbol: "GMRINFRA.NS", name: "GMR Airports Infra" },
  { symbol: "IRB.NS", name: "IRB Infrastructure" },
  { symbol: "ASHOKA.NS", name: "Ashoka Buildcon" },
  { symbol: "NCC.NS", name: "NCC" },
  { symbol: "PNCINFRA.NS", name: "PNC Infratech" },
  { symbol: "HG INFRA.NS", name: "H.G. Infra Engineering" },
  { symbol: "HGINFRA.NS", name: "H.G. Infra Engineering" },
  // Real Estate
  { symbol: "BRIGADE.NS", name: "Brigade Enterprises" },
  { symbol: "MAHLIFE.NS", name: "Mahindra Lifespace" },
  { symbol: "SOBHA.NS", name: "Sobha" },
  { symbol: "SUNTECK.NS", name: "Sunteck Realty" },
  { symbol: "PHOENIXLTD.NS", name: "Phoenix Mills" },
  { symbol: "ANANTRAJ.NS", name: "Anant Raj" },
  { symbol: "KOLTEPATIL.NS", name: "Kolte-Patil Developers" },
  { symbol: "LODHA.NS", name: "Macrotech Developers (Lodha)" },
  { symbol: "MACROTECH.NS", name: "Macrotech Developers (Lodha)" },
  { symbol: "EMBASSY.NS", name: "Embassy Office Parks REIT" },
  { symbol: "MINDSPACE.NS", name: "Mindspace Business Parks REIT" },
  // Retail & Consumer
  { symbol: "SHOPERSTOP.NS", name: "Shoppers Stop" },
  { symbol: "FCONSUMER.NS", name: "Future Consumer" },
  { symbol: "TITAN.NS", name: "Titan Company" },
  { symbol: "KALYANKJIL.NS", name: "Kalyan Jewellers" },
  { symbol: "THANGAMAYIL.NS", name: "Thangamayil Jewellery" },
  { symbol: "SENCO.NS", name: "Senco Gold" },
  { symbol: "PVRINOX.NS", name: "PVR Inox" },
  { symbol: "SAREGAMA.NS", name: "Saregama India" },
  { symbol: "NAZARA.NS", name: "Nazara Technologies" },
  { symbol: "PLAYGAMES.NS", name: "PlayGames24x7" },
  // Defence & Railways
  { symbol: "BDL.NS", name: "Bharat Dynamics" },
  { symbol: "BEML.NS", name: "BEML" },
  { symbol: "RVNL.NS", name: "Rail Vikas Nigam" },
  { symbol: "RAILTEL.NS", name: "RailTel Corporation" },
  { symbol: "IRCON.NS", name: "IRCON International" },
  { symbol: "TITAGARH.NS", name: "Titagarh Rail Systems" },
  { symbol: "TEXRAIL.NS", name: "Texmaco Rail & Engineering" },
  { symbol: "AIAENG.NS", name: "AIA Engineering" },
  { symbol: "BHEL.NS", name: "Bharat Heavy Electricals" },
  { symbol: "MIDHANI.NS", name: "Mishra Dhatu Nigam" },
  { symbol: "MITA.NS", name: "MSTC" },
  { symbol: "MSTCLTD.NS", name: "MSTC" },
  // New-age tech / startups listed
  { symbol: "CARTRADE.NS", name: "CarTrade Tech" },
  { symbol: "EASEMYTRIP.NS", name: "Easy Trip Planners" },
  { symbol: "IXIGO.NS", name: "Le Travenues Technology (Ixigo)" },
  { symbol: "YATRA.NS", name: "Yatra Online" },
  { symbol: "MATRIMONY.NS", name: "Matrimony.com" },
  { symbol: "JUST DIAL.NS", name: "Just Dial" },
  { symbol: "JUSTDIAL.NS", name: "Just Dial" },
  { symbol: "AFFLE.NS", name: "Affle India" },
  { symbol: "INDIGOPNTS.NS", name: "Indigo Paints" },
  { symbol: "CAMPUS.NS", name: "Campus Activewear" },
  { symbol: "CAMS.NS", name: "Computer Age Management Services" },
  { symbol: "CDSL.NS", name: "Central Depository Services India" },
  { symbol: "BSE.NS", name: "BSE (Bombay Stock Exchange)" },
  { symbol: "MCX.NS", name: "Multi Commodity Exchange" },
  // Insurance
  { symbol: "LICI.NS", name: "Life Insurance Corp of India (LIC)" },
  { symbol: "NIACL.NS", name: "New India Assurance" },
  { symbol: "STARHEALTH.NS", name: "Star Health & Allied Insurance" },
  { symbol: "ICICIGI.NS", name: "ICICI Lombard General Insurance" },
  { symbol: "HDFCAMC.NS", name: "HDFC AMC" },
  { symbol: "NIPPONLIFE.NS", name: "Nippon India Mutual Fund" },
  { symbol: "UTIAMC.NS", name: "UTI AMC" },
  // Agrochemicals / Specialty Chemicals
  { symbol: "SUMICHEM.NS", name: "Sumitomo Chemical India" },
  { symbol: "PIIND.NS", name: "PI Industries" },
  { symbol: "DHANUKA.NS", name: "Dhanuka Agritech" },
  { symbol: "RALLIS.NS", name: "Rallis India" },
  { symbol: "ASTEC.NS", name: "Astec Lifesciences" },
  { symbol: "BALRAMCHIN.NS", name: "Balrampur Chini Mills" },
  { symbol: "TRIVENI.NS", name: "Triveni Engineering" },
  { symbol: "RENUKA.NS", name: "Shree Renuka Sugars" },
  { symbol: "SRF.NS", name: "SRF" },
  { symbol: "ALKYLAMINE.NS", name: "Alkyl Amines Chemicals" },
  { symbol: "CLEAN.NS", name: "Clean Science & Technology" },
  { symbol: "FINEORG.NS", name: "Fine Organic Industries" },
  { symbol: "ROSSARI.NS", name: "Rossari Biotech" },
  // Cement
  { symbol: "ACC.NS", name: "ACC Cement" },
  { symbol: "AMBUJACEM.NS", name: "Ambuja Cements" },
  { symbol: "DALMIACEME.NS", name: "Dalmia Bharat" },
  { symbol: "JKCEMENT.NS", name: "JK Cement" },
  { symbol: "RAMCOCEM.NS", name: "Ramco Cements" },
  { symbol: "HEIDELBERG.NS", name: "Heidelberg Cement" },
  { symbol: "ORIENTCEM.NS", name: "Orient Cement" },
  // Retail Banks (small/mid)
  { symbol: "NUVOCO.NS", name: "Nuvoco Vistas" },
  { symbol: "STARCEMENT.NS", name: "Star Cement" },
  { symbol: "BIRLACORPN.NS", name: "Birla Corporation" },
  // Telecom & Media
  { symbol: "TATACOMM.NS", name: "Tata Communications" },
  { symbol: "HATHWAY.NS", name: "Hathway Cable & Datacom" },
  { symbol: "DEN.NS", name: "DEN Networks" },
  { symbol: "SUNTV.NS", name: "Sun TV Network" },
  { symbol: "ZEEL.NS", name: "Zee Entertainment" },
  { symbol: "TV18BRDCST.NS", name: "TV18 Broadcast (CNBC-TV18)" },
  { symbol: "NETWORK18.NS", name: "Network18 Media" },
  { symbol: "PVRINOX.NS", name: "PVR Inox" },
  // Aviation & Logistics
  { symbol: "BLUEDART.NS", name: "Blue Dart Express" },
  { symbol: "DELHIVERY.NS", name: "Delhivery" },
  { symbol: "GATI.NS", name: "Gati Kintetsu Express" },
  { symbol: "MAHLOG.NS", name: "Mahindra Logistics" },
  { symbol: "TCI.NS", name: "Transport Corporation of India" },
  { symbol: "SPICEJET.NS", name: "SpiceJet" },
  { symbol: "JETAIRWAYS.NS", name: "Jet Airways" },
  // PSU & Government
  { symbol: "MTNL.NS", name: "MTNL" },
  { symbol: "NBCC.NS", name: "NBCC India" },
  { symbol: "HUDCO.NS", name: "Housing & Urban Development Corp" },
  { symbol: "IDBI.NS", name: "IDBI Bank" },
  { symbol: "OBC.NS", name: "Oriental Bank of Commerce" },
  { symbol: "MAHABANK.NS", name: "Bank of Maharashtra" },
  { symbol: "IOB.NS", name: "Indian Overseas Bank" },
  { symbol: "CENTRALBK.NS", name: "Central Bank of India" },
  { symbol: "UCOINDIA.NS", name: "UCO Bank" },
];

export function searchStocks(query: string, limit = 10) {
  if (!query || query.trim().length < 1) return [];
  const q = query.toLowerCase().trim();

  const results = NSE_STOCKS.filter(s =>
    s.symbol.toLowerCase().replace('.ns','').includes(q) ||
    s.name.toLowerCase().includes(q)
  );

  // Prioritize: exact symbol match → starts with query → contains query
  results.sort((a, b) => {
    const aSym = a.symbol.toLowerCase().replace('.ns','');
    const bSym = b.symbol.toLowerCase().replace('.ns','');
    const aName = a.name.toLowerCase();
    const bName = b.name.toLowerCase();
    const aExact = aSym === q || aName === q ? 0 : aSym.startsWith(q) || aName.startsWith(q) ? 1 : 2;
    const bExact = bSym === q || bName === q ? 0 : bSym.startsWith(q) || bName.startsWith(q) ? 1 : 2;
    return aExact - bExact;
  });

  return results.slice(0, limit);
}
